### ISSUE TITLE
missing modules on Linux

### ISSUE THREAD

**Issue by mburo** [Blizzard/s2protocol#63]
After cloning the repository and running
  python setup.py install --user
on a Fedora 26 machine, issuing
  s2_cli.py --versions
results in 

Traceback (most recent call last):
  File "/usr/bin/s2_cli.py", line 4, in <module>
    __import__('pkg_resources').run_script('s2protocol==3.19.1.58600.5', 's2_cli.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 741, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1502, in run_script
    exec(code, namespace, namespace)
  File "/home/mic/.local/lib/python2.7/site-packages/s2protocol-3.19.1.58600.5-py2.7.egg/EGG-INFO/scripts/s2_cli.py", line 14, in <module>
    import attributes as _attr
ImportError: No module named attributes

On other occasions I saw "versions" reported missing, but I didn't take note what triggered it.

I then tried to run s2_cli.py in directory s2protocol like so:
  ./s2_cli.py --versions
resulting in:

Traceback (most recent call last):
  File "./s2_cli.py", line 374, in <module>
    main()
  File "./s2_cli.py", line 243, in main
    files = versions.list_all()
AttributeError: 'module' object has no attribute 'list_all'

Looking for list_all revealed that it is used like this:  ...versions.list_all() but there is no versions.py in the repository.

Any help regarding this would be much appreciated - I am trying to go through a million replays, but replaying them using the engine takes WAY too long.

**Comment by jrepp** [comment]
Please re-test. I accidentally removed some stuff when I was updating the new automated protocol files in s2protocol/versions. I had only fixed that on the py3 branch but pulled that fix in for master.
